### ISSUE TITLE
Can't Get Validation to Work.

### ISSUE THREAD

**Issue by noel-byT** [contentful/contentful-management.java#103]
Hey 👋,

I'm trying to generate some basic content types via. the contentful Java CMA API.
But I'm failing at the point of setting some linking validation rules on a content type.

I'm creating a plain old `CMAField` object:
```
CMAField blogEntry_modules = new CMAField();
blogEntry_modules.setName("Modules");
blogEntry_modules.setId("modules");
blogEntry_modules.setType(Constants.CMAFieldType.Array);
blogEntry_modules.setArrayItems(arrayItems);
blogEntry_modules.setValidations(validations);
```

`arrayItems` is filled with those items:
```
arrayItems.put("linkType", "Entry");
arrayItems.put("type", "Link");
```

I'm trying to add a validation to only link to specific content types, like in the example Web App from Contentful (https://github.com/contentful/the-example-app.nodejs). I took the "Lesson" Content Type as an example. You can link to multiple, other content types such as "Lesson > Copy" and so on.

Now I'm trying to put together my `validations` List.
```
List<Map> validations = new ArrayList<>();

// Add allowed content types.
Map<String, List<String>> allowedContentTypes = new HashMap<>();

// Create list of allowed content type ids.
List<String> allowedTypes = new ArrayList<>();
allowedTypes.add("blogEntry_copy");

// Put it in the Map.
allowedContentTypes.put("linkContentType", allowedTypes);

// Put it in the List.
validations.add(allowedContentTypes);
```

When I fire it through a Jackson ObjectMapper it generates a valid JSON String, the exact same one as the "Lesson" Content Type reference.

I get the following error:
`java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 12 column 19 path $.details.errors[0].value`

The desired content type is not being created. Without the validations field it works just fine.

Im grateful for every help!

// sorry for my bad English, I'm from Germany. :P //

**Comment by noel-byT** [comment]
I've just reviewed the requests that are being made in the Contentful Web app when a new content type is created.

The `validations` property remains completely ignored. The validation options are stored in the `items` property. A bit confusing, as it is not documented anywhere and the SDK has no sign of it.

Considering the code above, my solutions looks like this, as simple as it is:
`arrayItems.put("validations", validations);`

So, I think the `validations` property is deprecated?

**Comment by noel-byT** [comment]
Ah, I get it. The `validation` field is for input related validations.
Sorry, my fault. 😅

**Comment by noel-byT** [comment]
Hey @mariobodemann,

sorry for my late answer!


UX wise the SDK is absolutely fine. I think it would be cool, if more of these "edge cases" would be documented more code examples. You only find tiny bits of code (e.g. for content type creation). That'd be awesome.

**Comment by mariobodemann** [comment]
Thank you for the feedback, we will be thinking 🤔 about a way of exposing more edge case code...
