### ISSUE TITLE
com.contentful.java.cma.model.CMASpace.getDefaultLocale() is always null

### ISSUE THREAD

**Issue by adrian-baker** [contentful/contentful-management.java#112]

**Comment by mariobodemann** [comment]
This is true.

We did not want to introduce a backwards incompatible change. The API does not return the default locale on a CMA space anymore. If you want find out which locale is the default one, please take a look at [the documentation on how to fetch locles](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/locales/locale-collection/get-all-locales-of-a-space/console/java) and filter the responses by its `isDefault` property.

I hope I understood your question the right way, and hope I could additionally answer it.

Greetings,
Mario

**Comment by adrian-baker** [comment]
Thanks for explaining - perhaps the method could be annotated with `@Deprecated`, along with a comment pointing to the separate locales api? 

Also, I would suggest throwing an `UnsupportedOperationException`, rather than just returning null, would be preferable.

**Comment by mariobodemann** [comment]
Hey,

thanks for your feedback we will be iterating on it.

For now I will be closing this issue. Please feel free to reach out to us anytime.

Greetings,
Mario
