### ISSUE TITLE
Unable to update rich text field content back using the CMA-SDK 3.2.1

### ISSUE THREAD

**Issue by swapnil16899** [contentful/contentful-management.java#115]
HI,
I am using cma sdk 3.2.1 in my project. Using the sdk to fetch rich text field, in the response few keys are missing for example data, target inside data. but same thing i am able to get using the api through postman. So while the updating the content back i get exceptions.

below is and example: when I do get field using sdk i get following 
```
{
  "content": [
    {
      "content": [
        {
          "marks": [],
          "value": "this is normal text.",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    },
    {
      "level": 1,
      "content": [
        {
          "marks": [],
          "value": "Heading 1",
          "nodeType": "text"
        }
      ],
      "nodeType": "heading-1"
    },
    {
      "__level__": 2,
      "content": [
        {
          "marks": [],
          "value": "Heading 2",
          "nodeType": "text"
        }
      ],
      "nodeType": "heading-2"
    },
    {
      "content": [
        {
          "marks": [
            {
              "type": "bold",
              "object": "mark"
            }
          ],
          "value": "Bold ",
          "nodeType": "text"
        },
        {
          "marks": [
            {
              "type": "italic",
              "object": "mark"
            }
          ],
          "value": "italic ",
          "nodeType": "text"
        },
        {
          "marks": [
            {
              "type": "underline",
              "object": "mark"
            }
          ],
          "value": "underline",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    },
    {
      "content": [
        {
          "marks": [],
          "value": "<a href=\"https://www.w3schools.com\">This is a link</a>\n\n",
          "nodeType": "text"
        },
        {
          "data": "https://www.w3schools.com/html/html_attributes.asp",
          "content": [
            {
              "marks": [],
              "value": "link to url",
              "nodeType": "text"
            }
          ],
          "nodeType": "hyperlink"
        },
        {
          "marks": [],
          "value": "",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    },
    {
      "content": [
        {
          "marks": [],
          "value": "",
          "nodeType": "text"
        },
        {
          "data": {
            "sys": {
              "contentType": null,
              "createdAt": null,
              "createdBy": null,
              "firstPublishedAt": null,
              "id": "6EhRweAN9e8m6OseA4muMI",
              "linkType": "Entry",
              "publishedAt": null,
              "publishedBy": null,
              "publishedCounter": null,
              "publishedVersion": null,
              "space": null,
              "environment": null,
              "type": "Link",
              "updatedAt": null,
              "updatedBy": null,
              "version": null,
              "archivedVersion": null,
              "status": null
            }
          },
          "content": [
            {
              "marks": [],
              "value": "link to entry",
              "nodeType": "text"
            }
          ],
          "nodeType": "hyperlink"
        },
        {
          "marks": [],
          "value": "",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    },
    {
      "content": [
        {
          "content": [
            {
              "content": [
                {
                  "marks": [],
                  "value": "option1",
                  "nodeType": "text"
                }
              ],
              "nodeType": "paragraph"
            }
          ],
          "nodeType": "list-item"
        },
        {
          "content": [
            {
              "content": [
                {
                  "marks": [],
                  "value": "option2",
                  "nodeType": "text"
                }
              ],
              "nodeType": "paragraph"
            }
          ],
          "nodeType": "list-item"
        }
      ],
      "nodeType": "unordered-list"
    },
    {
      "content": [
        {
          "marks": [],
          "value": "",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    },
    {
      "content": [
        {
          "marks": [],
          "value": "",
          "nodeType": "text"
        }
      ],
      "nodeType": "paragraph"
    }
  ],
  "nodeType": "document"
}
```

and in postman for field i get the following response:

```
{
                "data": {},
                "content": [
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "this is normal text.",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 1",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-1"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 2",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-2"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "bold"
                                    }
                                ],
                                "value": "Bold ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "italic"
                                    }
                                ],
                                "value": "italic ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "underline"
                                    }
                                ],
                                "value": "underline",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "<a href=\"https://www.w3schools.com\">This is a link</a>\n\n",
                                "nodeType": "text"
                            },
                            {
                                "data": {
                                    "uri": "https://www.w3schools.com/html/html_attributes.asp"
                                },
                                "content": [
                                    {
                                        "data": {},
                                        "marks": [],
                                        "value": "link to url",
                                        "nodeType": "text"
                                    }
                                ],
                                "nodeType": "hyperlink"
                            },
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            },
                            {
                                "data": {
                                    **"target"**: {
                                        "sys": {
                                            "id": "6EhRweAN9e8m6OseA4muMI",
                                            "type": "Link",
                                            "linkType": "Entry"
                                        }
                                    }
                                },
                                "content": [
                                    {
                                        "data": {},
                                        "marks": [],
                                        "value": "link to entry",
                                        "nodeType": "text"
                                    }
                                ],
                                "nodeType": "entry-hyperlink"
                            },
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "content": [
                                    {
                                        "data": {},
                                        "content": [
                                            {
                                                "data": {},
                                                "marks": [],
                                                "value": "option1",
                                                "nodeType": "text"
                                            }
                                        ],
                                        "nodeType": "paragraph"
                                    }
                                ],
                                "nodeType": "list-item"
                            },
                            {
                                "data": {},
                                "content": [
                                    {
                                        "data": {},
                                        "content": [
                                            {
                                                "data": {},
                                                "marks": [],
                                                "value": "option2",
                                                "nodeType": "text"
                                            }
                                        ],
                                        "nodeType": "paragraph"
                                    }
                                ],
                                "nodeType": "list-item"
                            }
                        ],
                        "nodeType": "unordered-list"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    }
                ],
                "nodeType": "document"
            }
```

If you notice the highlighted are two of the difference between both response.

So while updating the field i get following error:
```
{
    "sys": {
        "type": "Error",
        "id": "InvalidEntry"
    },
    "message": "Validation error",
    "details": {
        "errors": [
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    0,
                    "data"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"level\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    1,
                    "level"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    1,
                    "data"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"level\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    2,
                    "level"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    2,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    3,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    4,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    5,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    6,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    7,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    8,
                    "data"
                ]
            },
            {
                "name": "required",
                "details": "The property \"data\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "data"
                ]
            }
        ]
    },
    "requestId": "a1285eb5736294b7637eafc35c7626f7"
}
```

**Comment by mariobodemann** [comment]
Hello, 

thank you for this feedback. I changed the formatting to find out if I can understand the underlying issue some more. I will need to investigate just a bit more to see what the root cause of the error is.

Thanks, 
Mario

**Comment by swapnil16899** [comment]
@mariobodemann 

When can we expect this to be fixed. Please can we have ETA for this fix?

**Comment by swapnil16899** [comment]
hey Mario,

when can we expect the release to be made as I still see snapshot in the version. I see the build status as failing. Once the official release is made I can test it with Postman.

**Comment by mariobodemann** [comment]
Hey,

I'm not sure how you will test a java sdk with postmann, but you should be able to proceed since the library is released now.

Greetings,
Mario

**Comment by swapnil16899** [comment]
hi,

Even after updating the cma-sdk version to 3.2.2, when I try updating the entry, I get following error:

FAILED ErrorBody { details = Details { errors = [Error { details = The property "level" is not expected, name = unexpected, path = [fields, field1, de-DE, content, 3.0, level], }, Error { details = The property "level" is not expected, name = unexpected, path = [fields, field1, de-DE, content, 4.0, level], }, Error { details = The property "level" is not expected, name = unexpected, path = [fields, field1, en-US, content, 3.0, level], }, Error { details = The property "level" is not expected, name = unexpected, path = [fields, field1, en-US, content, 4.0, level], }], }, message = Validation error, requestId = 48c256b3fc76344dead17b957f30c46d, sys = Sys { id = InvalidEntry, type = Error } }


Body: 
{
  "fields": {
    "field1": {
      "de-DE": {
        "content": [
          {
            "nodeType": "hr",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "hr",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "this is normal text.",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "level": 1,
            "content": [
              {
                "marks": [],
                "value": "Heading 1",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "heading-1",
            "data": {}
          },
          {
            "level": 2,
            "content": [
              {
                "marks": [],
                "value": "Heading 2",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "heading-2",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [
                  {
                    "type": "bold",
                    "object": "mark"
                  }
                ],
                "value": "Bold ",
                "nodeType": "text",
                "data": {}
              },
              {
                "marks": [
                  {
                    "type": "italic",
                    "object": "mark"
                  }
                ],
                "value": "italic ",
                "nodeType": "text",
                "data": {}
              },
              {
                "marks": [
                  {
                    "type": "underline",
                    "object": "mark"
                  }
                ],
                "value": "underline",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "<a href=\"https://www.w3schools.com\">This is a link</a>\n\n",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [
                  {
                    "marks": [],
                    "value": "link to url",
                    "nodeType": "text",
                    "data": {}
                  }
                ],
                "nodeType": "hyperlink",
                "data": {
                  "uri": "https://www.w3schools.com/html/html_attributes.asp"
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [
                  {
                    "marks": [],
                    "value": "link to entry",
                    "nodeType": "text",
                    "data": {}
                  }
                ],
                "nodeType": "entry-hyperlink",
                "data": {
                  "target": {
                    "sys": {
                      "type": "Link",
                      "linkType": "Entry",
                      "id": "6EhRweAN9e8m6OseA4muMI"
                    }
                  }
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "content": [
                  {
                    "content": [
                      {
                        "marks": [],
                        "value": "option1",
                        "nodeType": "text",
                        "data": {}
                      }
                    ],
                    "nodeType": "paragraph",
                    "data": {}
                  }
                ],
                "nodeType": "list-item",
                "data": {}
              },
              {
                "content": [
                  {
                    "content": [
                      {
                        "marks": [],
                        "value": "option2",
                        "nodeType": "text",
                        "data": {}
                      }
                    ],
                    "nodeType": "paragraph",
                    "data": {}
                  }
                ],
                "nodeType": "list-item",
                "data": {}
              }
            ],
            "nodeType": "unordered-list",
            "data": {}
          },
          {
            "content": [],
            "nodeType": "embedded-entry-block",
            "data": {
              "target": {
                "sys": {
                  "type": "Link",
                  "linkType": "Entry",
                  "id": "4nwMj5kpq8gGsqAiiC6Aey"
                }
              }
            }
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [],
                "nodeType": "embedded-entry-block",
                "data": {
                  "target": {
                    "sys": {
                      "type": "Link",
                      "linkType": "Entry",
                      "id": "W0CHeZQYKY8oCA8mCASMA"
                    }
                  }
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          }
        ],
        "nodeType": "document",
        "data": {}
      },
      "en-US": {
        "content": [
          {
            "nodeType": "hr",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "hr",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "this is normal text.",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "level": 1,
            "content": [
              {
                "marks": [],
                "value": "Heading 1",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "heading-1",
            "data": {}
          },
          {
            "level": 2,
            "content": [
              {
                "marks": [],
                "value": "Heading 2",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "heading-2",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [
                  {
                    "type": "bold",
                    "object": "mark"
                  }
                ],
                "value": "Bold ",
                "nodeType": "text",
                "data": {}
              },
              {
                "marks": [
                  {
                    "type": "italic",
                    "object": "mark"
                  }
                ],
                "value": "italic ",
                "nodeType": "text",
                "data": {}
              },
              {
                "marks": [
                  {
                    "type": "underline",
                    "object": "mark"
                  }
                ],
                "value": "underline",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "<a href=\"https://www.w3schools.com\">This is a link</a>\n\n",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [
                  {
                    "marks": [],
                    "value": "link to url",
                    "nodeType": "text",
                    "data": {}
                  }
                ],
                "nodeType": "hyperlink",
                "data": {
                  "uri": "https://www.w3schools.com/html/html_attributes.asp"
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [
                  {
                    "marks": [],
                    "value": "link to entry",
                    "nodeType": "text",
                    "data": {}
                  }
                ],
                "nodeType": "entry-hyperlink",
                "data": {
                  "target": {
                    "sys": {
                      "type": "Link",
                      "linkType": "Entry",
                      "id": "6EhRweAN9e8m6OseA4muMI"
                    }
                  }
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "content": [
                  {
                    "content": [
                      {
                        "marks": [],
                        "value": "option1",
                        "nodeType": "text",
                        "data": {}
                      }
                    ],
                    "nodeType": "paragraph",
                    "data": {}
                  }
                ],
                "nodeType": "list-item",
                "data": {}
              },
              {
                "content": [
                  {
                    "content": [
                      {
                        "marks": [],
                        "value": "option2",
                        "nodeType": "text",
                        "data": {}
                      }
                    ],
                    "nodeType": "paragraph",
                    "data": {}
                  }
                ],
                "nodeType": "list-item",
                "data": {}
              }
            ],
            "nodeType": "unordered-list",
            "data": {}
          },
          {
            "content": [],
            "nodeType": "embedded-entry-block",
            "data": {
              "target": {
                "sys": {
                  "type": "Link",
                  "linkType": "Entry",
                  "id": "4nwMj5kpq8gGsqAiiC6Aey"
                }
              }
            }
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              },
              {
                "content": [],
                "nodeType": "embedded-entry-block",
                "data": {
                  "target": {
                    "sys": {
                      "type": "Link",
                      "linkType": "Entry",
                      "id": "W0CHeZQYKY8oCA8mCASMA"
                    }
                  }
                }
              },
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          },
          {
            "content": [
              {
                "marks": [],
                "value": "",
                "nodeType": "text",
                "data": {}
              }
            ],
            "nodeType": "paragraph",
            "data": {}
          }
        ],
        "nodeType": "document",
        "data": {}
      }
    },
    "title": {
      "de-DE": "second",
      "en-US": "second"
    }
  }
}


After removing the unexpected "Level" , I see the following error:

{
    "sys": {
        "type": "Error",
        "id": "InvalidEntry"
    },
    "message": "Validation error",
    "details": {
        "errors": [
            {
                "name": "required",
                "details": "The property \"content\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    0,
                    "content"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    5,
                    "content",
                    0,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    5,
                    "content",
                    1,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    5,
                    "content",
                    2,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "in",
                "details": "Value must be one of expected values",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    10,
                    "content",
                    1,
                    "nodeType"
                ],
                "value": "embedded-entry-block",
                "expected": [
                    "asset-hyperlink",
                    "embedded-entry-inline",
                    "entry-hyperlink",
                    "hyperlink"
                ]
            },
            {
                "name": "required",
                "details": "The property \"content\" is required here",
                "path": [
                    "fields",
                    "field1",
                    "en-US",
                    "content",
                    0,
                    "content"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "en-US",
                    "content",
                    5,
                    "content",
                    0,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "en-US",
                    "content",
                    5,
                    "content",
                    1,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "unexpected",
                "details": "The property \"object\" is not expected",
                "path": [
                    "fields",
                    "field1",
                    "en-US",
                    "content",
                    5,
                    "content",
                    2,
                    "marks",
                    0,
                    "object"
                ]
            },
            {
                "name": "in",
                "details": "Value must be one of expected values",
                "path": [
                    "fields",
                    "field1",
                    "en-US",
                    "content",
                    10,
                    "content",
                    1,
                    "nodeType"
                ],
                "value": "embedded-entry-block",
                "expected": [
                    "asset-hyperlink",
                    "embedded-entry-inline",
                    "entry-hyperlink",
                    "hyperlink"
                ]
            }
        ]
    },
    "requestId": "f4f5159119a24d9e92cf2b181c9b188a"
}


So I am not sure what all are required properties for updation of entry. 
My question here is the properties which are not expected then why they are present in the the cma models. Please can you check on this.

**Comment by wzhang-openhouse** [comment]
We see a new error after pulling the CMA-SDK 3.2.2
`{ details = Details { errors = [Error { details = The property "object" is not expected, name = unexpected, path = [fields, seoMetaDescription, en-US, content, 0.0, content, 0.0, marks, 0.0, object], }, Error { details = The property "object" is not expected, name = unexpected, path = [fields, seoMetaDescription, en-US, content, 0.0, content, 2.0, marks, 0.0, object], }, Error { details = The property "object" is not expected, name = unexpected, path = [fields, seoMetaDescription, en-US, content, 0.0, content, 4.0, marks, 0.0, object], }, Error { details = The property "object" is not expected, name = unexpected, path = [fields, seoMetaDescription, en-US, content, 0.0, content, 6.0, marks, 0.0, object], }], }, message = Validation error, requestId = 3deb01202943c96c41aec466d5aadc1a, sys = Sys { id = InvalidEntry, type = Error } }
`

After investigation, we noticed that the retrieved Rich Text field does not contain the the "object" attribute but your new library automatically inserted the "object" attribute which caused the issue. see retrieved data below:
`{
   "en-US":{
      "data":{

      },
      "content":[
         {
            "data":{

            },
            "content":[
               {
                  "data":{

                  },
                  "marks":[
                     {
                        "type":"italic"
                     }
                  ],
                  "value":"The Winston",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":"'s ",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[
                     {
                        "type":"bold"
                     }
                  ],
                  "value":"L-shaped kitchen",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":" is designed to inspire the pursuit of the culinary arts. There is ample space for all your gadgets and a fabulous eating bar for guests to sit and watch while you show off your culinary skills. The ",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[
                     {
                        "type":"bold"
                     }
                  ],
                  "value":"main floor pocket office",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":" is strategically located away from disruption allowing for privacy to get your work done. The ",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[
                     {
                        "type":"bold"
                     }
                  ],
                  "value":"master suite",
                  "nodeType":"text"
               },
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":" has a massive walk-in closet and luxurious 5-piece ensuite.",
                  "nodeType":"text"
               }
            ],
            "nodeType":"paragraph"
         },
         {
            "data":{

            },
            "content":[
               {
                  "data":{

                  },
                  "content":[
                     {
                        "data":{

                        },
                        "content":[
                           {
                              "data":{

                              },
                              "marks":[

                              ],
                              "value":"Test",
                              "nodeType":"text"
                           }
                        ],
                        "nodeType":"paragraph"
                     }
                  ],
                  "nodeType":"list-item"
               },
               {
                  "data":{

                  },
                  "content":[
                     {
                        "data":{

                        },
                        "content":[
                           {
                              "data":{

                              },
                              "marks":[

                              ],
                              "value":"Test",
                              "nodeType":"text"
                           }
                        ],
                        "nodeType":"paragraph"
                     }
                  ],
                  "nodeType":"list-item"
               }
            ],
            "nodeType":"unordered-list"
         },
         {
            "data":{

            },
            "content":[
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":"paragraph 2",
                  "nodeType":"text"
               }
            ],
            "nodeType":"paragraph"
         },
         {
            "data":{

            },
            "content":[
               {
                  "data":{

                  },
                  "content":[
                     {
                        "data":{

                        },
                        "content":[
                           {
                              "data":{

                              },
                              "marks":[

                              ],
                              "value":"test 11",
                              "nodeType":"text"
                           }
                        ],
                        "nodeType":"paragraph"
                     }
                  ],
                  "nodeType":"list-item"
               },
               {
                  "data":{

                  },
                  "content":[
                     {
                        "data":{

                        },
                        "content":[
                           {
                              "data":{

                              },
                              "marks":[

                              ],
                              "value":"test 22",
                              "nodeType":"text"
                           }
                        ],
                        "nodeType":"paragraph"
                     }
                  ],
                  "nodeType":"list-item"
               }
            ],
            "nodeType":"ordered-list"
         },
         {
            "data":{

            },
            "content":[
               {
                  "data":{

                  },
                  "marks":[

                  ],
                  "value":"",
                  "nodeType":"text"
               }
            ],
            "nodeType":"paragraph"
         }
      ],
      "nodeType":"document"
   }
}`

See your SDK generated JSON object below:
`"seoMetaDescription":{  
         "en-US":{  
            "content":[  
               {  
                  "content":[  
                     {  },
                     {  },
                     {  
                        "marks":[  
                           {  
                              "type":"bold",
                              "object":"mark"
                           }
                        ],
                        "value":"L-shaped kitchen",
                        "nodeType":"text",
                        "data":{  

                        }
                     },
                     {  
                        "marks":[  

                        ],
                        "value":" is designed to inspire the pursuit of the culinary arts. There is ample space for all your gadgets and a fabulous eating bar for guests to sit and watch while you show off your culinary skills. The ",
                        "nodeType":"text",
                        "data":{  

                        }
                     },
                     {  
                        "marks":[  
                           {  
                              "type":"bold",
                              "object":"mark"
                           }
                        ],
                        "value":"main floor pocket office",
                        "nodeType":"text",
                        "data":{  

                        }
                     },
                     {  
                        "marks":[  

                        ],
                        "value":" is strategically located away from disruption allowing for privacy to get your work done. The ",
                        "nodeType":"text",
                        "data":{  

                        }
                     },
                     {  
                        "marks":[  
                           {  
                              "type":"bold",
                              "object":"mark"
                           }
                        ],
                        "value":"master suite",
                        "nodeType":"text",
                        "data":{  

                        }
                     },
                     {  
                        "marks":[  

                        ],
                        "value":" has a massive walk-in closet and luxurious 5-piece ensuite.",
                        "nodeType":"text",
                        "data":{  

                        }
                     }
                  ],
                  "nodeType":"paragraph",
                  "data":{  

                  }
               }
            ],
            "nodeType":"document",
            "data":{  

            }
         }`

And see your code in **com.contentful.java.cma.model.rich.CMARichMark** as put a final field private **final String object = "mark";** which will always insert the "object":"mark"

We made some hacks to remove that field then the error goes away. Please fix them accordingly

**Comment by mariobodemann** [comment]
Hey,

this issue got overlooked by me. The `marks` are not yet supported properly, so I will update them soon™.

Sadly I cannot give you a timeline on the marks issue, and will come back on you once I got a fix for it.

If you feel you are able to contribute a PR to it, this would be increasing time drastically.

Greetings,
Mario

**Comment by mariobodemann** [comment]
We just release v3.2.4, fixing the marker serialization.

Please feel free to report any more missing rich text elements in a new ticket.
