### ISSUE TITLE
Unable to update richtext field having hyperlink / Embeded entries

### ISSUE THREAD

**Issue by swapnil16899** [contentful/contentful-management.java#122]
HI Mario,

I have rich text field in my content model which has HyperLinks and embedded entry. I fetch the object returned and try to update the target locale field with the object, I am not able to update it and I get following error.

422 Unprocessable Entity

Response body:

{
    "sys": {
        "type": "Error",
        "id": "InvalidEntry"
    },
    "message": "Validation error",
    "details": {
        "errors": [
            {
                "name": "in",
                "details": "Value must be one of expected values",
                "path": [
                    "fields",
                    "field1",
                    "de-DE",
                    "content",
                    2,
                    "nodeType"
                ],
                "value": "hyperlink",
                "expected": [
                    "blockquote",
                    "embedded-asset-block",
                    "embedded-entry-block",
                    "heading-1",
                    "heading-2",
                    "heading-3",
                    "heading-4",
                    "heading-5",
                    "heading-6",
                    "hr",
                    "ordered-list",
                    "paragraph",
                    "unordered-list"
                ]
            }
        ]
    },
    "requestId": "734db8fb0d74e1c6d914f7cd79444a77"
}

I get same error if I have a hyperlink in my richtext field, or embeded entry,inline entry. There is clear a difference in the way these field is are returned through api using postman and through the CMA-SDK 3.2.4

I have attached both the response files to the ticket.

Postman Response file : 
[PostmanResponse.txt](https://github.com/contentful/contentful-management.java/files/2880278/PostmanResponse.txt)

Cma-Sdk file:
[CMA-SDK_Response.txt](https://github.com/contentful/contentful-management.java/files/2880281/CMA-SDK_Response.txt)

differences: 

When the nodeType is hyperlink, there is difference in the data key. One returns object and other returns directly the link.
Second, when the nodeType is embedded-entry-block, one returns data which has a target which contains the entry and other returns data which directly returns the entry. for difference you can check the files attached.

Please can you check on this.

**Comment by mariobodemann** [comment]
Hello,

thank you for reaching out, I am sorry for seeing there is trouble with the rich text.

I am surprised to see this error popping up actually, because that is exactly what we are testing at in the [e2e tests](https://github.com/contentful/contentful-management.java/blob/master/src/test/kotlin/com/contentful/java/cma/e2e/RichTextE2E.kt#L256-L290).

Do you mind sharing the layout of the rich text field in Contentful or the direct response from Contentful? Maybe there is something wrong with the test setup or the model. Let's find out together...

**Comment by swapnil16899** [comment]
![image](https://user-images.githubusercontent.com/46025247/53089429-940c9400-3532-11e9-9876-58274dc8a942.png)


My richtext field looks like this. it pretty basic. in the end it has on hyperlingk and one embedded entry.
Please let me know if you anything else.

**Comment by swapnil16899** [comment]
HI @mariobodemann do we have any update on this. Also the helper function for the rich text talk about converting Json to Html. This can be useful while fetching and exporting the content. Is there anything which can used to convert the Html back to Json and update the richtext or can we use the Html directly to update the rich text field?

**Comment by mariobodemann** [comment]
Hello,

my priorities are currently shifted, and I didn't had enough time to fully grasp the problem. You could help me with trying to send me the json response of this entry by either using `curl` to retrieve the item or using network logging on the java sdk.

For your second question: No, there is no current know way on how to convert html to rich text.

Greetings,
Mario

**Comment by swapnil16899** [comment]
Following is the Json response when I retrieve the entry : 
{
    "sys": {
        "space": {
            "sys": {
                "type": "Link",
                "linkType": "Space",
                "id": "em7vz7wkf4bi"
            }
        },
        "id": "27385G93tuekey8QYyckgc",
        "type": "Entry",
        "createdAt": "2018-12-18T08:53:27.217Z",
        "updatedAt": "2019-03-01T07:43:51.842Z",
        "environment": {
            "sys": {
                "id": "master",
                "type": "Link",
                "linkType": "Environment"
            }
        },
        "publishedVersion": 87,
        "publishedAt": "2019-02-19T12:32:20.783Z",
        "firstPublishedAt": "2018-12-20T11:52:20.942Z",
        "createdBy": {
            "sys": {
                "type": "Link",
                "linkType": "User",
                "id": "7pvpSfXQZ3BKDZBHc4p8ho"
            }
        },
        "updatedBy": {
            "sys": {
                "type": "Link",
                "linkType": "User",
                "id": "7pvpSfXQZ3BKDZBHc4p8ho"
            }
        },
        "publishedCounter": 7,
        "version": 98,
        "publishedBy": {
            "sys": {
                "type": "Link",
                "linkType": "User",
                "id": "7pvpSfXQZ3BKDZBHc4p8ho"
            }
        },
        "contentType": {
            "sys": {
                "type": "Link",
                "linkType": "ContentType",
                "id": "richTextType"
            }
        }
    },
    "fields": {
        "field1": {
            "de-DE": {
                "data": {},
                "content": [
                    {
                        "data": {},
                        "content": [],
                        "nodeType": "hr"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "hr",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "this is normal text.",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 1",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-1"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 2",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-2"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "bold"
                                    }
                                ],
                                "value": "Bold ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "italic"
                                    }
                                ],
                                "value": "italic ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "underline"
                                    }
                                ],
                                "value": "underline",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "code"
                                    }
                                ],
                                "value": "<a href=\"https://www.w3schools.com\">This is a link</a>\n",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [],
                                "value": "\n",
                                "nodeType": "text"
                            },
                            {
                                "data": {
                                    "uri": "https://www.w3schools.com/html/html_attributes.asp"
                                },
                                "content": [
                                    {
                                        "data": {},
                                        "marks": [],
                                        "value": "",
                                        "nodeType": "text"
                                    }
                                ],
                                "nodeType": "hyperlink"
                            },
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "content": [
                                    {
                                        "data": {},
                                        "marks": [],
                                        "value": "this is a block quote",
                                        "nodeType": "text"
                                    }
                                ],
                                "nodeType": "paragraph"
                            }
                        ],
                        "nodeType": "blockquote"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    }
                ],
                "nodeType": "document"
            },
            "en-US": {
                "data": {},
                "content": [
                    {
                        "data": {},
                        "content": [],
                        "nodeType": "hr"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "hr",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "this is normal text.",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 1",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-1"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "Heading 2",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "heading-2"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "bold"
                                    }
                                ],
                                "value": "Bold ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "italic"
                                    }
                                ],
                                "value": "italic ",
                                "nodeType": "text"
                            },
                            {
                                "data": {},
                                "marks": [
                                    {
                                        "type": "underline"
                                    }
                                ],
                                "value": "underline",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "marks": [],
                                "value": "",
                                "nodeType": "text"
                            },
                            {
                                "data": {
                                    "uri": "https://www.w3schools.com/html/html_attributes.asp"
                                },
                                "nodeType": "hyperlink",
                                "content": [
                                    {
                                        "nodeType": "text",
                                        "value": "",
                                        "marks": [],
                                        "data": {}
                                    }
                                ]
                            },
                            {
                                "data": {},
                                "nodeType": "text",
                                "value": "<head><title>My Website</title></head>",
                                "marks": [
                                    {
                                        "type": "code"
                                    }
                                ]
                            },
                            {
                                "data": {},
                                "marks": [],
                                "value": "\n\n",
                                "nodeType": "text"
                            }
                        ],
                        "nodeType": "paragraph"
                    },
                    {
                        "data": {},
                        "content": [
                            {
                                "data": {},
                                "nodeType": "paragraph",
                                "content": [
                                    {
                                        "nodeType": "text",
                                        "value": "this is a block quote",
                                        "marks": [],
                                        "data": {}
                                    }
                                ]
                            }
                        ],
                        "nodeType": "blockquote"
                    },
                    {
                        "nodeType": "paragraph",
                        "content": [
                            {
                                "nodeType": "text",
                                "value": "",
                                "marks": [],
                                "data": {}
                            },
                            {
                                "nodeType": "hyperlink",
                                "content": [
                                    {
                                        "nodeType": "text",
                                        "value": "this is hyperlink text",
                                        "marks": [],
                                        "data": {}
                                    }
                                ],
                                "data": {
                                    "uri": "https://jsonformatter.org/"
                                }
                            },
                            {
                                "nodeType": "text",
                                "value": "",
                                "marks": [],
                                "data": {}
                            }
                        ],
                        "data": {}
                    },
                    {
                        "nodeType": "embedded-entry-block",
                        "content": [],
                        "data": {
                            "target": {
                                "sys": {
                                    "id": "34MlmiuMgU8wKCOOIkAuMy",
                                    "type": "Link",
                                    "linkType": "Entry"
                                }
                            }
                        }
                    },
                    {
                        "nodeType": "paragraph",
                        "content": [
                            {
                                "nodeType": "text",
                                "value": "",
                                "marks": [],
                                "data": {}
                            }
                        ],
                        "data": {}
                    }
                ],
                "nodeType": "document"
            }
        },
        "title": {
            "de-DE": "this is rich text example",
            "en-US": "second"
        }
    }
}

**Comment by swapnil16899** [comment]
Attaching Respone file when I retrieve the entry : 

[Response.txt](https://github.com/contentful/contentful-management.java/files/2918437/Response.txt)

**Comment by swapnil16899** [comment]
HI Mario,

Do you have any update on this. I have logged one more ticket regarding SDK.

**Comment by mariobodemann** [comment]
Hello and thank you for your continues interest in our SDK.

I will address your question in the [new ticket](#123), and close this one.
