### ISSUE TITLE
The type of \"data\" is incorrect, expected type: Object

### ISSUE THREAD

**Issue by swapnil16899** [contentful/contentful-management.java#123]
Hi,

I have a content type which has rich text field. The content has a Link to Url (Hyperlink). When I try to update the field using rest api I get following error.

ERROR :-   The type of \"data\" is incorrect, expected type: Object

There is a clear difference in the way entry field is returned using the Api and SDK.
From Api I get like below : 
"data": {
     "uri": "https://www.w3schools.com/html/html_attributes.asp"
 }

From SDK I get as below :
"data": "https://www.w3schools.com/html/html_attributes.asp"

So as the error state it expects object while updating. So If I modify the SDK response and make it same as API response the error doesn't show up.

Please can you fix that so that SDK returns data as an object and not as KeyValue pair.

**Comment by mariobodemann** [comment]
Hello,

I just merged both tickets into this one, so we only have one ticket dealing with the same issue.

I just created a test case, trying to emulate the behaviour you are facing. I wrote this code snippet as an end to end test, using the newest SDK:

```kotlin
        val linkedEntry = CMAEntry().setId("6VkkamQ5zO4qWIugKkWowK")

        val richText = CMARichDocument().addContent(
                CMARichParagraph().addContent(
                        CMARichHyperLink("https://contentful.org/").addContent(
                                CMARichText("this is hyperlink text"))
                ),
                CMARichEmbeddedLink(CMALink(linkedEntry)),
                CMARichParagraph().addContent(
                        CMARichHyperLink("https://www.w3schools.com/html/html_attributes.asp"),
                        CMARichText("<head><title>My Website</title></head>", listOf(CMARichMark.CMARichMarkCode())),
                        CMARichText("\n\n")
                )
        )

        val richEntry = CMAEntry().setField("rich_text", "en-US", richText)

        val result = client.entries().create("theOnlyContentModel", richEntry)
        assertNotNull(result)

        val fetched = client.entries().fetchOne(result.id)

        val gson = GsonBuilder()
                .registerTypeAdapter(CMAEntry::class.java, EntrySerializer())
                .create()

        assertEquals(
                gson.toJson(richEntry.getField<CMARichNode>("rich_text", "en-US")),
                gson.toJson(fetched.getField<CMARichNode>("rich_text", "en-US"))
        )
    }
```

This test passes: I am able to create an entry as wanted by the API. This entry I created is a condensed example of your reported error in #122.

Can you try and see if you can create an entry with hyperlinks like I did above? If you can't we know a bit more and can dig down on how to solve your current issue. If you can create the entry by executing aboves code, we might have a solution for your issue too.

Greetings,
Mario

**Comment by rafalniski** [comment]
Closing for now. Please reopen if issue is still happening.
