### ISSUE TITLE
CMAHttpException fails to parse server response in constructor

### ISSUE THREAD

**Issue by vaano94** [contentful/contentful-management.java#142]
CMAHttpException uses GSON to parse the response from the server.

In case when the server returns an unsuccessful result, and the result _can not_ be parsed by GSON, the reason, why the request failed, will never be logged.
```
try {
      final String body = response.body() != null ? response.body().string() : null;
      this.errorBody = new GsonBuilder().create().fromJson(body, ErrorBody.class);
    } catch (IOException e) {
      this.errorBody = null; 
    }
```

**Comment by jepfp** [comment]
and as a result the parsing of the error itself turns into an exception.

**Comment by rafalniski** [comment]
Closing for now, will consider changing how we handle HTTP error responses
