### ISSUE TITLE
Should this call super?

### ISSUE THREAD

**Issue by marta-rey-benito** [contentful/contentful-management.java#147]
Hello there, 
I am getting a  `java.lang.StackOverflowError` exception when calling the `.getId()` method of the CMATag class. It looks like a typo : 

```
  @Override public String getId() {
    return getId();  // Should it be super.getId() ?
  }
```
https://github.com/contentful/contentful-management.java/blob/master/src/main/java/com/contentful/java/cma/model/CMATag.java#L87

In case it helps I have raised a PR to fix the typo: https://github.com/contentful/contentful-management.java/pull/148

Thanks!

**Comment by rafalniski** [comment]
Thanks, indeed. I merged the PR.
