### ISSUE TITLE
Support to fetch organization data when fetching CMASpace entities

### ISSUE THREAD

**Issue by niketkhandelwal** [contentful/contentful-management.java#150]
The CMA API endpoint `GET /spaces` returns `organization` property within the `sys` property of a space, but the same is not returned when using the CMA SDK v3.4.2 to fetch spaces. Please consider this feature request.

**Comment by niketkhandelwal** [comment]
If it helps, I've added the required changes in pull request #151

**Comment by rafalniski** [comment]
@niketkhandelwal Thanks, I merged it.
