### ISSUE TITLE
Unable to change limit on Webhook calls method

### ISSUE THREAD

**Issue by haydnsimons** [contentful/contentful-management.java#154]
Hello,

I've just updated to SDK version 3.4.4 following the fix for this issue https://github.com/contentful/contentful-management.java/issues/149. I am now trying to use the SDK to retrieve a list of webhook calls with a specified limit. As far as I can see, this functionality isn't possible for webhook calls as you can't pass in a query parameter (unlike how it can be done in the webhooks fetchAll method). I have pasted a simple java application below to show how it works for the fetchAll method but how it's not possible for the calls method.  

import com.contentful.java.cma.CMAClient;
import com.contentful.java.cma.model.CMAArray;
import com.contentful.java.cma.model.CMAWebhook;

public class Application {
	private final static String TOKEN = "PERSONAL_ACCESS_TOKEN";
	private final static String SPACE = "SPACE_ID";

	public static void main(String[] args) {
		CMAClient client = new CMAClient
				.Builder()
				.setAccessToken(TOKEN)
				.setSpaceId(SPACE)
				.build();

            //CAN successfully limit number of webhooks returned from this call by populating the 'query' parameter.
            CMAArray<CMAWebhook> array = client.webhooks().fetchAll(SPACE_ID, query);
    
            //Fetch the webhook for the space and id.
            final CMAWebhook webhook = client.webhooks().fetchOne(SPACE_ID, WEBHOOK_ID);

            //Fetch all the call for a specific webhook (would like to specify a limit for this call)
            //CANNOT limit the number of calls returned and it always defaults to a limit of 20
            final CMAArray<CMAWebhookCall> calls = client.webhooks().calls(webhook);

            //Ideally this would also have accept a second 'query' parameter (Map<String, String>) as shown below
            final CMAArray<CMAWebhookCall> calls = client.webhooks().calls(webhook, query);
	    }
}

Is this functionality something that could be added to the SDK?
Thanks in advance!

**Comment by amartinez-forrester** [comment]
Same problem here. We are using a custom Web Client to "temporally" solve this problem. 
Apart from that, the webhook endpoint is not working well, you need to call /health endpoint first to see the number of actual calls there. 
The default "total" result is buggy and by default has "20", even if you have more calls in the buffer.
Call to /heatlh endpoint example:
```json
{
    "sys": {
        "id": "myId",
        "type": "Webhook",
        "space": {
            "sys": {
                "type": "Link",
                "linkType": "Space",
                "id": "mySpace"
            }
        },
        "createdBy": {
            "sys": {
                "type": "Link",
                "linkType": "WebhookDefinition",
                "id": "myWebhook"
            }
        }
    },
    "calls": {
        "total": 500,
        "healthy": 294
    }
}
```
And when you hit /calls endpoint, the total count has always the "limit" value:
![image](https://user-images.githubusercontent.com/101810839/189368137-019b57dd-9ab9-4fa4-baaf-00bb2c6f6e07.png)

Summarizing, we have two problems that need a solution: 
1) Fix the total field in the response that comes from the /calls endpoint, in my example, this number should be "500", not "30".
2) Add the feature that @haydnsimons is asking for to avoid using a custom web client.

Regards,
Agustin

**Comment by rafalniski** [comment]
Hey @haydnsimons 
This should be resolved in: https://github.com/contentful/contentful-management.java/pull/158
I will make a new release soon.

@amartinez-forrester 
I raised the issue with the Contentful API team, will let you know when I have some feedback.

**Comment by rafalniski** [comment]
@haydnsimons This is now available in `v.3.4.6`

**Comment by amartinez-forrester** [comment]
Thank you @rafalniski

**Comment by haydnsimons** [comment]
Thanks @rafalniski!

**Comment by amartinez-forrester** [comment]
@rafalniski Hi, did the contentful api team solve the API problem? (the total field in the response that comes from the /calls endpoint)

**Comment by rafalniski** [comment]
Hey @amartinez-forrester, I was told it should be fixed now. Can you check if it works correctly on your side, please?

**Comment by amartinez-forrester** [comment]
It is working, great. Thanks!
