### ISSUE TITLE
Support for bulk actions endpoint?

### ISSUE THREAD

**Issue by jake-netflix** [contentful/contentful-management.java#155]
There is an API endpoint in CMA for bulk publishing ([example](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/bulk-actions/publish-bulk-action/publish-bulk-action/console/java)), but it is not supported in this SDK. Can that be added?

**Comment by rafalniski** [comment]
Hey @jake-netflix indeed it's not supported yet, but we may consider implementing it in the near future, can't tell ETA at the moment.

**Comment by rafalniski** [comment]
Hey @jake-netflix, sorry it took so long, bulk actions are now released in `v.3.4.10`
