### ISSUE TITLE
Having up-to-date docs / automize it

### ISSUE THREAD

**Issue by Swissbite** [contentful/contentful-management.java#159]
The gh-pages for the contentful management java API has it's last update **4 years ago**.
The link to the API Reference on https://www.contentful.com/developers/docs/java/sdks/ points to an outdated version of your implementation.

The docs should be an automated process after every version release. This can be done by github actions.

**Comment by rafalniski** [comment]
Hey @Swissbite,

there was recently an update of the documentation. Could you please check again? If something is still missing, don't hesitate to point that out!
