### ISSUE TITLE
Support Contentful Tags

### ISSUE THREAD

**Issue by Swissbite** [contentful/contentful-management.java#160]
Tags - a feature implemented roughly one year ago - is still not implemented in the contentful management java api.

We have a content transformation client - external source to contentful - and would like to have this included within this library, asap.
![image](https://user-images.githubusercontent.com/205621/199982155-8de8f140-3e33-410e-a301-6dde21303220.png)

**Comment by rafalniski** [comment]
Hey @Swissbite,

content tags are supported in the library, documentation was also updated recently: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/content-tags/tag/get-a-single-tag/console/kotlin

Sorry for the delay!
