### ISSUE TITLE
removing leading slashes for paths from requests

### ISSUE THREAD

**Issue by omeratila7** [contentful/contentful-management.java#162]
cma-sdk is using retrofit 2 and sending requests with leading slashes ("/") and as mentioned in retrofits documentation (https://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#baseUrl-okhttp3.HttpUrl-) if endpoint have leading slash it ignores the path of base url. and it causes the bugs if base url have path at url. there is a PR about that issue. can you review it

**Comment by rafalniski** [comment]
Thanks! Released in v.3.4.7
