### ISSUE TITLE
Please, add opportunity to set default values for ContentType fields

### ISSUE THREAD

**Issue by Deses0005** [contentful/contentful-management.java#168]
According to the REST API documentation we able in contentful specify [default values for ContentType](https://www.contentful.com/developers/docs/references/content-management-api/#default-values), but on CMAField.java there is no such field. Could you add please opportunity to provide default values for specific fields in contentful ?

**Comment by rafalniski** [comment]
Hey @Deses0005 , added this in `v.3.4.9`
