### ISSUE TITLE
Concern Regarding CMAEntry Serialization During Entry Creation

### ISSUE THREAD

**Issue by Xchg0x5f375d** [contentful/contentful-management.java#173]
Dear Contentful Community,

I'd like to bring to your attention an issue I've encountered while utilizing the Java SDK's CMAEntry, specifically regarding its support for metadata and tags. It appears that when attempting to create a CMAEntry with populated tags, the metadata property is being overlooked during serialization of the request. Consequently, any content already populated with metadata, such as tags, is being ignored and not created with the specified metadata, i.e tags.

While I acknowledge that this may be an oversight in a recently implemented feature, I wanted to confirm if this is indeed the case. My experience with Contentful is somewhat limited, so I may be mistaken. However, after testing with Curl and .js SDKs, I've found that this issue does not persist, likely due to differences in implementation.

To address this issue, I have forked the project and made modifications to the EntrySerializer class to ensure that the metadata field is properly serialized. Upon testing, it appears that this solution resolves the problem.

Given that we heavily rely on this feature in our workflows, we would greatly appreciate it if this enhancement could be integrated into Contentful. I have already reached out via the Discord channel regarding this matter, but have not yet received any responses.

Thank you for your attention to this matter. We look forward to your response and a potential resolution.

**Comment by Xchg0x5f375d** [comment]
Hi @rafalniski,

Despite my attempt to initiate a discussion on Discord, I haven't received any responses or feedback yet. If possible, I would appreciate any feedback or insights that could help resolve this issue.

**Comment by rafalniski** [comment]
Hey @Xchg0x5f375d,

would you be able to create PR with your forked branch so that I can take a look at the changes?

**Comment by Xchg0x5f375d** [comment]
> Hey @Xchg0x5f375d,
> 
> would you be able to create PR with your forked branch so that I can take a look at the changes?

Thanks for the reply, appreciated. I've created a PR so we can now discuss the changes.

**Comment by rafalniski** [comment]
@Xchg0x5f375d This one is released in `v.3.4.11`
