### ISSUE TITLE
Add support for rich text tables in CMA

### ISSUE THREAD

**Issue by ilp** [contentful/contentful-management.java#175]
While working with the Contentful Java SDK, I observed that the CMAEntry object does not currently support table elements. As tables are an essential component of rich content, it is important to include support for mapping tables within the Content Management API (CMA).

I propose adding support for table mapping in CMA, similar to what already exists in the [com.contentful.java.cda.rich](https://github.com/contentful/contentful.java/tree/master/src/main/java/com/contentful/java/cda/rich) package. It is crucial that mapping of all rich text elements works consistently in both the Content Delivery API (CDA) and CMA, to provide a cohesive and comprehensive development experience.

Your consideration of this feature request is greatly appreciated. Thank you for your attention to this matter.

**Comment by rafalniski** [comment]
@ilp This should now be supported in `v.3.4.12`

**Comment by ilp** [comment]
Thanks 🚀🚀
