### ISSUE TITLE
Support reading schedule details

### ISSUE THREAD

**Issue by meldmy** [contentful/contentful-management.java#183]
![image](https://github.com/user-attachments/assets/e773357e-69ac-42e2-9a57-5d31e358e933)

Hu guys, right now, there is no ability to create a proper report with info about entries since we cannot fetch schedule information

**Comment by meldmy** [comment]
I assume that we can extend https://github.com/contentful/contentful-management.java/blob/master/src/main/java/com/contentful/java/cma/model/CMAEntry.java like we already did with tags

**Comment by meldmy** [comment]
@rafalniski 🙏🏻

**Comment by rafalniski** [comment]
Hey @meldmy,

I created PR with the initial implementation, please let me know if anything is missing!
