### ISSUE TITLE
Unable to create entry with "Object" field

### ISSUE THREAD

**Issue by jonsie** [contentful/contentful-management.java#26]
I am unable to create an entry with a Contentful "Object" field.  In the example below (written in Groovy) the field "links" is an Object field in Contentful:

```
CMAEntry entry = new CMAEntry()
String locale = 'en'
String links = '[{"displayOrder": 1, "linkType": "URL", "linkValue": "https://www.example.com", "audienceType": "ALL", "s3AssetUrl": null, "linkName": "foo"}, {"displayOrder": 2, "linkType": "URL", "linkValue": "https://www.example.com", "audienceType": "ALL", "s3AssetUrl": null, "linkName": "bar"}]'

entry.setField('name', 'Test Name', locale)
entry.setField('links', links, locale)
```
and then later in the code:
```
client.entries().create(spaceId, contentTypeId, entry)
```

This always results in a "422 Unprocessable Entity" error.  This API is working perfectly for all other field types, but I can not get this one to work.  Please help!

**Comment by tomxor** [comment]
Since you're setting the value of the field as a string it will be sent as a string to the API, when in fact the API expects raw JSON for this type of field. One way to achieve this is to bundle the values into a `Map` instance, and use `entry.setField('links', map, locale)` - the client will use GSON to convert this Map to JSON and saving should work fine.

**Comment by tomxor** [comment]
I just noticed you are creating an array of objects, this means you need to create a list of maps, i.e.:

```groovy
def links = [
    [
      displayOrder: 1,
      linkType: "URL",
      linkValue: "https://www.example.com",
      audienceType: "ALL",
      s3AssetUrl: null,
      linkName: "foo"
    ],
    [
      displayOrder: 2,
      linkType: "URL",
      linkValue: "https://www.example.com",
      audienceType: "ALL",
      s3AssetUrl: null,
      linkName: "bar"
    ]
]

entry.setField('links', links, locale)
```

**Comment by jonsie** [comment]
Of course!  I was using JsonOutput to serialize the Groovy object to a JSON string, so I'll just send it through JsonSlurper and that should do it.

Thanks for the tip!

**Comment by tomxor** [comment]
np! :)
