### ISSUE TITLE
Support search parameters

### ISSUE THREAD

**Issue by RobeEW** [contentful/contentful-management.java#36]
At present it is not possible to retrieve entries by content type as it is not possible to pass the search query param to the http client. It is also not possible to pass the skip or limit query parameters. So fetchAll does not fetch all, it only fetches 100, and there is no way to get at the rest unless you already know their ids.

**Comment by tomxor** [comment]
@RobeEW :+1: I'll try to add support for that soon.

**Comment by tomxor** [comment]
This has been merged, I will release 0.9.8 today so you don't have to wait for 1.0, will post here once it is out.

**Comment by tomxor** [comment]
Pushed to SonaType, so 0.9.8 should be available via Maven Central within the next 10 minutes.

**Comment by RobeEW** [comment]
Great, thanks!

**Comment by tomxor** [comment]
@RobeEW np, thanks for the report!
