### ISSUE TITLE
Is there a fully functional open-source web app like ghost available using contentful API ?

### ISSUE THREAD

**Issue by ishandutta2007** [contentful/contentful-management.java#44]
I am looking for a full fledged web app like https://ghost.org/

**Comment by grncdr** [comment]
Hi @ishandutta2007 I don't know of any (open source) projects like that. I assume you've taken a look at app.contentful.com and found it wanting?

**Comment by ishandutta2007** [comment]
Yes, I am using your example blogging app for android, now I need an example blogging website too. If its as comprehensive as ghost there is nothing like it, but was surprised to see just client library being given out in contentful-management.java but no websie.

**Comment by grncdr** [comment]
Ah I see, so you're looking for something more on the display side then the content-editing side? Or both?

**Comment by ishandutta2007** [comment]
I believe your site https://www.contentful.com uses contentful APIs,  is it's code opensourced  ?

**Comment by grncdr** [comment]
That specific site is not open-sourced unfortunately, but this is more due to lack of motivation than anything particularly private about it. I can tell you that the site is built using https://github.com/contentful/contentful_middleman, and we have a bunch of example sites in https://github.com/contentful-labs/contentful_middleman_examples that could serve as a starting point if you wanted to use a similar tool chain to publish a blog from Contentful.

**Comment by ishandutta2007** [comment]
I see but ROR is not a platform I am looking to build on, I am looking for a nodejs project.

**Comment by grncdr** [comment]
For node we have also created https://github.com/contentful-labs/contentful-metalsmith & https://github.com/contentful-labs/contentful-metalsmith-example, though these are currently not actively supported. Again, the example would need to be adapted but should be a good starting point for a blog.

**Comment by ishandutta2007** [comment]
metalsmith is for static but thanks.
To compete with ghost I guess eventually contentful will release some full fledged blogging platform.

**Comment by grncdr** [comment]
To be honest it's unlikely to happen any time soon, as blogging is more of a "small example project" use-case than a core focus for us.

Contentful is a better fit for larger projects with complex content models and a need to translate & re-use the content in many different contexts. A blog editing app could be built on top of our API's, and indeed there have been at least a couple of different projects along those lines, but nothing open source. The advantage in using Contentful for teams that have done this has been not needing to write or run any server side code, just deploying a static JS app out of S3 that uses our Content Management API.

On the other hand, the vast majority just use the default editing application at https://app.contentful.com (which is built and deployed in exactly the same way I just described).
