### ISSUE TITLE
Cannot Upload local asset files

### ISSUE THREAD

**Issue by lsamayoa** [contentful/contentful-management.java#45]
There is no way to upload Asset files in the SDK directly

**Comment by mariobodemann** [comment]
Hi,

you will be able to upload everything that has a non local url. So you would be able to upload it (temporarily) to google drive, dropbox, or any other 3rd party provider, and then create an asset, process it and publish it. Afterwards you can safely delete it from the 3rd party upload.

**Comment by lsamayoa** [comment]
Ok I will update the issue title

**Comment by mariobodemann** [comment]
Hey,

sorry, but it is just not possible to upload an asset to `contentful` directly. Please use a third-party upload library to receive a url containing your assets.

**Comment by Valerzen88** [comment]
Could you provide a working example?

**Comment by mariobodemann** [comment]
Hey,

sure, you would create an upload like this: 

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/uploads/upload-a-file/creating-an-upload-resource/console/android

and then create a new asset using the following snippet and the upload id from the previous step in the `uploadFrom` file field:

https://www.contentful.com/developers/docs/references/content-management-api/#/reference/assets/assets-collection/create-an-asset/console/android

In total it will look something like this:

~~~java
// initialize
final String spaceId = "SPACE_ID";
final String cmaToken = "CMA_TOKEN";
final String filePath = "FILE_PATH";

final CMAClient client = new CMAClient.Builder()
    .setAccessToken(cmaToken)
    .build();

// create binary upload
final CMAUpload cmaUpload = client
    .uploads()
    .create(
        spaceId,
        FileUtils.openInputStream(new File(filePath))
    );

// create asset
CMAAsset asset = new CMAAsset();
asset.getFields()
    .setTitle("en-US", "Title")
    .setDescription("en-US", "Picture");

CMAAssetFile file = new CMAAssetFile()
    .setUploadFrom(
        new CMALink(CMAType.Upload).setId(cmaUpload.getId())
    )
    .setFileName("filename.jpg")
    .setContentType("image/jpeg");

asset.getFields().setFile("en-US", file);

// create asset on contentful
asset = client.assets().create(spaceId, asset);

client.assets().process(asset, "en-US");

// wait till processing is done
String url = asset.getFields().localize("en-US").getFile().getUrl();
int attempts = 10;
while (attempts > 0 && (url == null || url.length() == 0)) {
  asset = client.assets().fetchOne(spaceId, asset.getId());
  url = asset.getFields().localize("en-US").getFile().getUrl();
  attempts--;

  try {
    Thread.sleep(500);
  } catch (Exception e) {
    e.printStackTrace();
  }
}

if (attempts <= 0) {
  throw new IllegalStateException("Could not finish processing for " + asset);
}

client.assets().publish(asset);
~~~

Greetings, 
Mario

**Comment by john007abhilash** [comment]
@mariobodemann how would we create an asset and assoiciate it with an Entry using java, just like it has been done over here using JavaScript https://github.com/contentful/contentful-management.js/issues/97#issuecomment-291836777

**Comment by john007abhilash** [comment]
Anyways i found out, 

  private def createEntry(assetId: String, storageId: String, categoryId: String, fileName: String, locale: String) = {
    var entry = new CMAEntry()
    var assetLink = new CMALink(CMAType.Asset).setId(assetId)
    var categoryLink = new CMALink(CMAType.Entry).setId(categoryId)
    var storageLink = new CMALink(CMAType.Entry).setId(storageId)
    entry.setField("name", locale, fileName)
    entry.setField("asset", locale, assetLink)
    entry.setField("category", locale, categoryLink)
    entry.setField("storage", locale, storageLink)
    entry.setField("type", locale, "image")
    entry = contentfulClient.entries().create("file", entry)
    contentfulClient.entries().publish(entry)
  }

**Comment by gredfearn** [comment]
@mariobodemann i've been having troubles with this even after the examples. One of the issues i am running into may be because i'm trying to create an asset from an upload on a specific environment. my code is trying  follows these steps:
1) create client
2) get space
3) get environment
4) environment.createUpload(data)
5) environment.createAsset({
      fields: {
            title: {
              'en-US': 'some title'
            },
            file: {
              'en-US': {
                fileName: 'some name',
                contentType: 'image/jpeg',
                uploadFrom: {
                  sys: {
                    type: 'Link',
                    linkType: 'Upload',
                    id: upload.sys.id
                  }
                }
              }
            }
          })
6) asset.processForAllLocales()
7) asset.publish()

This fails on step 5, creating the asset from the upload, giving me "The resource could not be found." error message. There isn't much for documentation accommodating `environment.createUpload()` and there was a deprecation warning on `space.createUpload()` as well, so I'm at a bit of a loss
