### ISSUE TITLE
Docs do not accurately represent how to update an entry using the async api

### ISSUE THREAD

**Issue by sortiz-sfdc** [contentful/contentful-management.java#46]
The following code block will yield retrofit error: `retrofit.RetrofitError: entry must have a space associated.`
```
//This code doesn't work
//Asynchronously update the entry
cmaClient.entries().async().update(cmaEntry, new CMACallback<CMAEntry>() {
    @Override protected void onSuccess(CMAEntry result) {
        System.out.println("Updated " + id);
    }
    @Override protected void onFailure(RetrofitError e) {
        System.out.println("Failed to update " + id);
	    e.printStackTrace();
    }
});
```

I had to resort to using the synchronous method to update my entry.

**Comment by mariobodemann** [comment]
Hello,

thanks for reaching out to us, this is really odd. Do you mind sharing how you created the `cmaEntry`?

**Comment by sortiz-sfdc** [comment]
I see what my original issue was. When I'm building up a CMAEntry that I know exists, I don't have any system attributes to set on my entry (like revision, etc). I have to query Contentful for that entry, then update only the fields that need to be updated. That's a little slow. Especially if I'm storing static HTML that will never change.
