### ISSUE TITLE
CMAField doesn't have a way to designate a field as localized

### ISSUE THREAD

**Issue by sortiz-sfdc** [contentful/contentful-management.java#47]
I can't programmatically tell a field to be localized when I'm creating a new ContentType. I have to manually do it using the UI. I can, however, specify if a field is localized in Ruby (at least I think I can). 

Using contentful-management.rb, I can do: 
` field.localized = field_yml["localized"] if not(field_yml["localized"].nil?) `

Here's how I'm setting it up in Java:
```
if (field.get("localized") != null) {
  //TODO: This doesn't exist? 
  //cmaField.setLocalized((boolean) field.get("localized"));
  System.out.println(cmaField.getName() + " should be localized");
}
```

**Comment by mariobodemann** [comment]
Hey, 

we just released a (new version)[https://github.com/contentful/contentful-management.java/releases/tag/cma-sdk-0.10.0], containing the `localized` field on `CMAField`. 

Enjoy.

**Comment by mariobodemann** [comment]
@sortiz-sfdc did the [aforementioned release](https://github.com/contentful/contentful-management.java/releases/tag/cma-sdk-0.10.0) help you?
