### ISSUE TITLE
Create space with locales and content tokens

### ISSUE THREAD

**Issue by clearsky** [contentful/contentful-management.java#61]
In the direct http request its possible to create a space with a specific locale and create api keys for this space. Since we use this for our cd/ci environment this would help us a lot, if the java-sdk would offer such methods, but I could not find it. Do you plan to implement the missing points?

curl --silent \
             --request POST \
             --header "Authorization:Bearer $CONTENTFUL_MANAGEMENT_ACCESS_TOKEN" \
             --header "Content-Type: application/vnd.contentful.management.v1+json" \
             --data-binary "{
                  \"name\": \"$CONTENTFUL_NAME_OF_NEW_SPACE\",
                  \"defaultLocale\": \"de-DE\"
                }" \
             https://api.contentful.com/spaces/ \

curl --silent \
                --request POST \
                --header "Authorization: Bearer $CONTENTFUL_MANAGEMENT_ACCESS_TOKEN" \
                --header "Content-Type: application/vnd.contentful.management.v1+json" \
                --data-binary "{ \
                     \"name\": \"$CONTENTFUL_NAME_OF_NEW_SPACE\" \
                   }" \
                https://api.contentful.com/spaces/$CONTENTFUL_SPACE_ID/api_keys \

**Comment by mariobodemann** [comment]
Hello,

I have good and a bad news for you: You can already create a space with an ID in Java: https://github.com/contentful/contentful-management.java/blob/master/src/main/java/com/contentful/java/cma/ModuleSpaces.java#L51

Sadly, the API token creation API is not yet part of the CMA. We are working on bringing the SDK on par with the REST API, but we have no timeline or date to be announced.

Greetings,
Mario

**Comment by monochromata** [comment]
Thanks for the hint at  https://github.com/contentful/contentful-management.java/blob/master/src/main/java/com/contentful/java/cma/ModuleSpaces.java#L51 . What we'd be interested in would be to specify a locale when creating a space via the Contentful management API.

**Comment by mariobodemann** [comment]
Hey,

sorry for the incredible delay. Sadly I also come back not just late, but also with bad news: You cannot create a space with a locale just yet. I'll put it on our to do list, but am not sure about the timeline of getting this in.

Mario

**Comment by mariobodemann** [comment]
Hey, 

I'm going through my open tickets and found this one still unattended. 😱

To answer your slightly old question: You have now a way of creating a space with the default locale set: 

```

final CMAClient client = new CMAClient.Builder()
    .setAccessToken(CMA_TOKEN).build();

final CMASpace space = new CMASpace()
    .setName("locales is mokale")
    .setDefaultLocale("foo");

CMASpace createdSpace = client.spaces().create(space, ORGANIZATION_ID);

final CMAArray<CMALocale> cmaLocaleCMAArray = client.spaces().fetchLocales(createdSpace.getId());
```

I hope it is still relevant to you, and will close this issue for now. Please feel free to reopen this one or create a new one if this does not solve your request.

Greetings, Mario
