### ISSUE TITLE
No support for editor interface manipulation?

### ISSUE THREAD

**Issue by KeesKoffeman** [contentful/contentful-management.java#63]
There's seems to be no support for manipulating the editor interface as described in the manual: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/editor-interface/editor-interface/update-the-editor-interface.

Am I missing something or is this simply not implemented?

**Comment by mariobodemann** [comment]
Hey @KeesKoffeman 

you are right, the Java SDK does not _currently_ support the editor interface endpoint. It is on our todo list, but sadly,  I cannot confirm a release date or schedule. I can only say stay tuned....

Greetings,
Mario

**Comment by mariobodemann** [comment]
Hey @KeesKoffeman ,

it's been some month, but we can report we have support for Editor Interfaces in 2.1.0. I hope it is still of use for you, and please feel free to check it out...

Closing this issue for now, please feel free to respond or create a new one if needed.
