### ISSUE TITLE
Mechanism for handling API rate limits

### ISSUE THREAD

**Issue by gaapt** [contentful/contentful-management.java#64]
It would be nice for the SDK to eventually introduce a mechanism to handle API rate limits, similar to the JS and Ruby SDKs:

https://github.com/contentful/contentful-management.js/blob/e818be53f7c7e42efd9e45912474af0a02f97136/lib/contentful-management.js#L37

https://github.com/contentful/contentful.rb#client-configuration-options

**Comment by mariobodemann** [comment]
Hello @gaapt,

that is a great idea. I will put it on our timeline, but sadly cannot confirm a release date or whether we'll be starting on working on it.

Greetings, 
Mario

**Comment by mariobodemann** [comment]
Hello again,

we just released a new [2.0.0 release](https://github.com/contentful/contentful-management.java/releases/tag/cma-sdk-2.0.0) with some minor support for rate limiting headers once an error is hit. We are thinking about a different approach to always return those headers, but we did not want to postpone the release any longer.

Does the current change already help you?

Greetings, 
Mario

**Comment by mariobodemann** [comment]
Additionally with [2.1.0](https://github.com/contentful/contentful-management.java/releases/tag/cma-sdk-2.1.0) we added a [rate limit listener](https://github.com/contentful/contentful-management.java/blob/master/src/main/java/com/contentful/java/cma/CMAClient.java#L446) to the client, getting called whenever a rate limit header is present in a response.

I hope that will fix this issue, at lease I'll close it for now, and I hope to hear back from you once tried...

Greetings,
Mario
