### ISSUE TITLE
How to auto-publish Entry updated with Java SDK.

### ISSUE THREAD

**Issue by cleber-henriques-ilegra** [contentful/contentful-management.java#74]
Hi,

I've updated some Entries in my space, but i noticed that the changes weren't published. After updating these entries, they changed their status to `Changed`.

Is there a way to "auto-publish` an update? What steps should i do so i don't need to publish each update?

Thanks in advance.

**Comment by cleber-henriques-ilegra** [comment]
Hey guys, nevermind... 

In my tests, i tried to publish an entry previously updated, but i was receiving a conflict error.
That's why i opened this issue.

After thinking about this problem, i noticed that the function `update` of `ModuleEntries` was returning the updated Entry and i should publish that Entry.

I think that the documentation could be more explicit about this. 
Thanks anyway :)

**Comment by mariobodemann** [comment]
Hey,

thanks for the feedback! And great that you got it solved. We will think about a better way of making the documentation more explicit in this case ... :)
