### ISSUE TITLE
Unable to retrieve image dimensions for image assets

### ISSUE THREAD

**Issue by dan-j** [contentful/contentful-management.java#94]
Library version:

`com.contentful.java:cma-sdk:2.1.0`

Retrieving an asset doesn't serialize the `image` field from `fields.file.details`. I think this is due to the class `com.contentful.java.cma.model.CMAAssetFile.Details` has two fields, `size` and `imageMeta`, however `imageMeta` should be named `image`, as per the JSON response.

Running a quick script in the debugger, inspecting the following property:

    this.allAssets.getItems().get(0).getFields().getFile("en-GB").getDetails()

Shows `imageMeta` as null, as pictured below:

![image](https://user-images.githubusercontent.com/5727701/29864791-1b3bd73a-8db7-11e7-8cbe-7d8c6af9b16d.png)

If I make a manual GET request using the Management API I get the following response, notice the dimensions are under a property named `image` not `imageMeta` (ignore the difference in field values, they're different assets but the problem persists for all assets):

```json
{
    "sys": {
        ...omitted
    },
    "fields": {
        "title": {
            "en-GB": "My Title"
        },
        "file": {
            "en-GB": {
                "url": "<my_url>",
                "details": {
                    "size": 21926456,
                    "image": {
                        "width": 5760,
                        "height": 3840
                    }
                },
                "fileName": "MyFilename.jpg",
                "contentType": "image/jpeg"
            }
        }
    }
}
```

**Comment by mariobodemann** [comment]
Hello,

that is a great bug report! And indeed, we are missing a `@SerializedName("image")` at the image meta field. Great spot, I'll create a bug fix for that soonish.

Thank you!

**Comment by dan-j** [comment]
Thanks! There's nothing more annoying than a bug report that is someone just complaining about something not working 😄 

While you're here, is there a reason the fields are read-only? 

I've been having issues with images over 20MB not properly processing (I'm currently in contact with support about it) and to workaround the issue I've had to write my own HttpRequests to make a PUT to /assets with updated URL and dimensions.

**Comment by mariobodemann** [comment]
No worries, we are working on creating the best SDK and product possible, so every input is appreciated ... ;)

Those fields are read only, since our internal asset handling will generate those fields. There is no way (or at least, there should be no way ;)) you can change them, except for reuploading and reprocessing of a new image.

**Comment by dan-j** [comment]
Ah, well yeah there is a way, just a PUT request with different `url` and `details` values and it updates. My issue is with images over 20MB are served with `url: "//downloads.contentful.com/...."` and dimensions weren't available. But if I copied the path from the url and used the "images" subdomain it worked, so I manually extracted the dimensions from my local files and updated the contentful data with those dimensions and changed the url to "images.contentful.com/..." and it works like a charm!

**Comment by mariobodemann** [comment]
Hmm,

that sounds like an interesting approach, sadly I can see some details about it:

0. Sadly, this behaviour is undocumented and might be removed/changed/updated at any point int time 😱
1. You will lose the ability to use the image api (cropping, rescaling, etc.) for images bigger then ~20 MB.
2. If you need the information about size and so on, you could create an intermediate content type, which store the information everytime you are creating an asset.
3. You could scale the images down before you upload them to Contentful, but that depends highly on your use case...

In the mean time, I created a bugfix PR, and am releasing a new version soon™...

**Comment by mariobodemann** [comment]
(and we have it released, please give it some hours to update the maven central, or what ever dependency repository you are using to try it out.)
