### ISSUE TITLE
Allow access to validation details in CMAHttpException

### ISSUE THREAD

**Issue by gkolpin** [contentful/contentful-management.java#98]
The `CMAHttpException` class doesn't appear to provide a way to access the `details` property on the response. According to [https://www.contentful.com/developers/docs/references/errors/](https://www.contentful.com/developers/docs/references/errors/), there should be a `details` section on the response that may contain information about validation issues occurring during attempted insert or update operations. Neither the `responseMessage` nor `toString` methods seem to contain enough information to determine failed validations. Additionally, the reference to the `response` object within `CMAHttpException` is declared private, preventing the raw data from being accessed and manually parsed.

**Comment by mariobodemann** [comment]
Hello,

that sounds like a great addition. I will put it on our backlog an tackle it accordingly.
